### ISSUE TITLE
Issue with font-icon

### ISSUE THREAD

**Issue by Migoo** [mkhairi/materialize-sass#30] opened 2015-05-01 09:22 UTC
Hello,

First of all, thanks for providing the Materialize amazingness to SASS.

Since we got a JS error, I'm using directly the github master branch in our project. We saw an issue with the Icon: the provided class didn't render the right icon. For example if I use 'mdi-action-home' it display the 'mdi-action-history' icon. All icon are wrong icon. I suppose the font was updated but the css was not updated to support the new font.

Thanks a lot for watching this.
Best regards

**Comment by mkhairi** [comment] 2015-05-04 22:25
@Migoo  thanks for reporting issue. will be fix for next release version. for now you can try update gem from git source (master) to test with latest updated assets.

**Comment by mkhairi** [comment] 2015-05-05 01:59
Okay i miss some info. You already on master branch. I will check current repo asset and fix this issues. Cheer :)

**Comment by xamenrax** [comment] 2015-05-05 09:06
@Migoo  Hm, actually this issue was fixed with pull-request for another issue. Check this out.

**Closed** 2015-05-05 09:06 UTC

**Comment by Migoo** [comment] 2015-05-07 14:28
Hi,

I just have a look, and now it's not working anymore. I got a 500 error when it try to get the font.
Any idea ?

ActionController::RoutingError (No route matches [GET] "/font/material-design-icons/Material-Design-Icons.ttf"):

Thanks for watching

**Comment by xamenrax** [comment] 2015-05-07 14:40
@Migoo can't reproduce that, I successfully used material design icons in my test project

**Comment by Migoo** [comment] 2015-05-07 15:37
Ok, I'll have a deeper look in our project and keep you in touch.

best regards

**Comment by Migoo** [comment] 2015-05-08 08:37
Hello,

No idea what I was doing, but refreshing the install of the gem fix it !

Thanks for helping
Best regards

**Comment by mkhairi** [comment] 2015-05-08 15:28
:thumbsup: :thumbsup:

**Comment by birajpaul600** [comment] 2019-02-24 18:24
birajpaul600@gmail.com
